### ISSUE TITLE
allow custom user-agent

### ISSUE THREAD

**Issue by qyloxe** [rnag/cert-hero#3]
Please allow custom user-agent setting. Unfortunately some hardened servers are blocking python requests:

https://github.com/rnag/cert-hero/blob/5a7edde6e2c37be30a3956689235822c4058d28a/cert_hero/cert_hero.py#L296

**Comment by rnag** [comment]
@qyloxe Thanks for creating this issue request! Please see #4

**Comment by rnag** [comment]
Done! The user-agent setting should be implemented as part of [v0.4](https://pypi.org/project/cert-hero/0.4.0/) 🎉
